### ISSUE TITLE
Overflow scroll

### ISSUE THREAD

**Issue by FLAK-ZOSO** [Alenygam/spaggiu#23]
- Browser: **Chrome 108.0.5359.100** (64 bits)

<img width="270" alt="image" src="https://user-images.githubusercontent.com/83119697/208254099-0b7dd7b5-1a7f-43c1-b6b7-df8008a78f7a.png">

Like when you set `overflow-x: scroll;` in CSS.

- https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

**Comment by Alenygam** [comment]
The website's styling is currently really ugly and incredibly dysfunctional, and it is due for a rewrite... I'll start working on it
